name: CI and releases
on:
  pull_request:
  push:
    branches: [main]

jobs:
  module-checks:
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-ci.yml@main
  example-self-checks:
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-ci.yml@main
    with:
      path: examples/self
  ci:
    needs:
      - module-checks
      - example-self-checks
    runs-on: ubuntu-latest
    steps:
      - run: "echo We have to define at least one step, even if it is not needed."

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-release.yml@main
