name: CI and releases
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-ci.yml@main

  release:
    needs: ci
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-release.yml@main
